# Generated by Django 5.2.8 on 2026-01-11 13:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('shelfID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isbn', models.CharField(max_length=17, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('year_of_publication', models.IntegerField(blank=True, null=True)),
                ('borrowable', models.BooleanField(default=True)),
                ('coverURL', models.URLField(blank=True, null=True)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.user')),
                ('shelfID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.shelf')),
            ],
        ),
    ]
