# Generated by Django 5.2.8 on 2026-01-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_ownerid_alter_shelf_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='visibility',
            field=models.CharField(choices=[('0', 'private'), ('1', 'friends'), ('2', 'public')], default='0', max_length=1),
        ),
    ]
